<?php
require_once"../../sessao.php";
?>
<div class="tabs-spacer" style="display:none;">
<?php
require_once("../../conexao.php");
$cfg->set_model_directory('../../models/');
?>
</div>
<form method="post" id="FrmFatGeral" class="uk-form" style="padding: 10px 0; margin-top: 0; "><label><span>Convênio</span> <select class="select " name="convenio_id" id="convenio_id" > <option value="">Selecionar Convênio</option>'<?php $descricaoconvenio=convenios::find('all',array('conditions'=>array('status=? and empresas_id=?',1,$COB_Empresa_Id)));$descricao=new ArrayIterator($descricaoconvenio);while($descricao->valid()):echo'<option value="'.$descricao->current()->id.'" >'.$descricao->current()->id." - ".utf8_encode($descricao->current()->nm_fantasia).'</option>';$descricao->next();endwhile;?> </select></label><label><span>Forma Cobrança</span> <select class="select " name="forma_cobranca" id="forma_cobranca" > <option>Aguardando...</option> </select></label><label><span>Plano</span> <select class="select " name="plano_id" id="plano_id" > <option>Aguardando...</option> </select></label><label><span>Forma reajuste</span><select class="select" name="tiporeajuste" id="tiporeajuste" > <option selected="selected">Selecionar</option> <option value="0">R$</option> <option value="1">%</option> </select></label><label><span>Reajuste (R$ / %)</span><input type="text" class="input_text center w_100" name="vreajuste" id="vreajuste" onblur="CalculaValor();"/></label><label><span>Valor Atual</span><input name="vatual" type="text" class="input_text center w_100" id="vatual" readonly="readonly"/></label><label><span>Valor reajustado</span><input name="vreajustado" type="text" class="input_text center w_100 camposleitura" id="vreajustado" readonly="readonly"/></label><a id="Btn_reaj_001" class="uk-button uk-button-primary" style="right:10px;margin-right:5px; position:absolute;bottom: 30px; line-height: 30px; width: 120px;" data-uk-tooltip="{pos:'left'}" title="Reajustar Valor" data-cached-title="Reajustar Valor" >Confirmar</a></form>


<script type="text/javascript">

eval(function(p,a,c,k,e,r){e=function(c){return(c<a?'':e(parseInt(c/a)))+((c=c%a)>35?String.fromCharCode(c+29):c.toString(36))};if(!''.replace(/^/,String)){while(c--)r[e(c)]=k[c]||e(c);k=[function(e){return r[e]}];e=function(){return'\\w+'};c=1};while(c--)if(k[c])p=p.replace(new RegExp('\\b'+e(c)+'\\b','g'),k[c]);return p}('5(\'#G\').T({S:\'R$ \',O:\'.\',X:\',\',W:H});5(\'#L\').T({S:\'R$ \',O:\'.\',X:\',\',W:H});5("#V").E(7(){t(5(m).6()==""){5("#F").k(\'<j>12 1r 14ê1e</j>\')}q{5("#F").k(\'<j>K ...</j>\');$.r("p/l/x.n",{z:0,V:5(m).6()},7(a){5("#F").k(a)})}});$("#F").E(7(){t(5(m).6()==""){5("#8").k(\'<j>12 1d 1c</j>\')}q{5("#8").k(\'<j>K ...</j>\');$.r("p/l/x.n",{z:1,1b:5(m).6()},7(a){5("#8").k(a)})}});$("#8").E(7(){t($(m).6()==""){5("#G").6(\'1a...\')}q{5("#G").6(\'M...\');$.r("p/l/x.n",{z:3,8:5(m).6()},7(a){5("#G").6(a)})}});5("#w").E(7(){t(5(m).6()==0){5("#s").P("I,I").Q()}q{5("#s").P("I").Q}});7 19(){9 b=5("#8").6();9 c=5("#s").6();9 d=5("#w").6();5("#L").6(\'M...\');$.r("p/l/x.n",{z:2,8:b,s:c,w:d},7(a){5("#L").6(a)})}5("#18").17(7(){9 g=5("#8").6();9 h=5("#s").6();9 i=5("#w").6();5("#10").k(" 16 15...");v.1h();$.r("p/l/x.n",{z:4,8:g,s:h,w:i},7(d){9 e=\'{"\'+d+\'"}\';9 f=11.Z(e);t(f.Y==1){A.B(\'\'+f.D+\'\',{C:y,u:\'U\'});v.J()}q{A.B(\'\'+f.D+\'\',{C:y,u:\'\'+f.u+\'\'});5("#10").k(" 1f 1g N 1iça");$.r("p/l/1j.n",{8:f.8},7(a){9 b=\'{"\'+a+\'"}\';9 c=11.Z(b);t(c.Y==1){A.B(\'\'+c.D+\'\',{C:y,u:\'U\'});v.J()}q{A.B(\'\'+c.D+\'\',{C:y,u:\'\'+c.u+\'\'});v.J();1k(7(){A.v.1l(\'1m 1n o 1o ?\',7(){1p(\'1q\',\'13\',\'13\',\'1s N 1t\',\'p/l/1u.n?8=\'+f.8+\'\',H,1v,\'K...\')})},y)}})}})});',62,94,'|||||jQuery|val|function|plano_id|var||||||||||option|html|planos|this|php||assets|else|post|vreajuste|if|status|modal|tiporeajuste|Controller_reajusta_planos|1000|acao|UIkit|notify|timeout|msg|change|forma_cobranca|vatual|true|99|hide|Carregando|vreajustado|Aguarde|de|thousands|mask|focus||prefix|maskMoney|danger|convenio_id|affixesStay|decimal|callback|parse|msg_loading|JSON|Selecione|200|conv|plano|Reajustando|click|Btn_reaj_001|CalculaValor|Aguardando|forma_cobranca_id|forma|uma|nio|Atualizando|dados|show|cobran|Controller_atualiza_d_cobranca|setTimeout|confirm|Deseja|Atualizar|faturamento|New_window|list|um|Reajuste|Parcelas|Frm_atualiza_fat|false'.split('|'),0,{}))
</script>
